server:
    port: 8081

spring:
    jpa:
        properties:
            hibernate:
                format_sql: true # 쿼리 포맷 설정
    data:
        mongodb:
            uri: mongodb://root:secret1!@localhost:27017/test?authSource=admin
            port: 27017
            auto-index-creation: true

