POST http://localhost:3000/api/orders/pre
Content-Type: application/json

{
    "token": "test-token",
    "orderItems": [
        {
            "productId": 1,
            "productName": "Running Shoes",
            "productPrice": 5000,
            "quantity": 1
        },
        {
            "productId": 2,
            "productName": "Sneakers",
            "productPrice": 5000,
            "quantity": 1
        }
    ]
}
